app:
  prefix: ''
  port: 3001
  swagger: false

upload:
  dest: './upload-test'

db:
  mysql:
    type: 'mysql'
    host: '127.0.0.1'
    port: 55001
    username: 'root'
    password: '123456'
    database: 'xiaoshop_test'
    charset: 'utf8mb4'
    timezone: '+08:00'
    logging: true
    logger: 'advanced-console'
    synchronize: false
    autoLoadEntities: true
  redis:
    host: '127.0.0.1'
    port: 6379
    db: 0

cache:
  keyPrefix: 'cache'
  db: 1
  ttl: 1
  max: 100

queue:
  prefix: 'queue'
  redis:
    db: 2
