api:
  prefix: '/test'
  port: 3002

upload:
  dest: './tests/__fixtures__/upload'

export:
  path: './tests/__fixtures__/backup'

mysql:
  type: 'mysql'
  host: '127.0.0.1'
  port: 55001
  username: 'root'
  password: '123456'
  database: 'xiaoshop_test'
  entityPrefix: 'xs_'
  charset: 'utf8mb4'
  dateStrings: true
  logging: false
  synchronize: false
  autoLoadEntities: true

redis:
  host: '127.0.0.1'
  port: 6379

cache:
  keyPrefix: 'cache'
  db: 3
  ttl: 5000
  max: 100

queue:
  prefix: 'queue'
  db: 4

jwt:
  adminSecret: 'XIAOSHOP_ADMIN_SECRET'
  shopSecret: 'XIAOSHOP_SHOP_SECRET'
  expiresIn: '1d'

http:
  timeout: 5000
  maxRedirects: 5
