import { MigrationInterface, QueryRunner } from 'typeorm'

export class LogisticsSettings1721566048207 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`INSERT INTO \`manage_settings\` (\`key\`, \`value\`) VALUES 
      ('logistics.deliveryMode.enableExpress', '1'),
      ('logistics.deliveryMode.enableLocal', '0'),
      ('logistics.deliveryMode.enableSelf', '0'),
      ('logistics.express.kd100.appKey', ''),
      ('logistics.express.kd100.customer', ''),
      ('logistics.selfPickup.days', '[1, 2, 3, 4, 5, 6, 7]'),
      ('logistics.selfPickup.timeFrames', '[["9:00", "23:00"]]'),
      ('logistics.selfPickup.timeStep', '30')
    `)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DELETE FROM \`manage_settings\` WHERE \`key\` IN (
      'logistics.deliveryMode.enableExpress',
      'logistics.deliveryMode.enableLocal',
      'logistics.deliveryMode.enableSelf',
      'logistics.express.kd100.appKey',
      'logistics.express.kd100.customer',
      'logistics.selfPickup.days',
      'logistics.selfPickup.timeFrames',
      'logistics.selfPickup.timeStep'
    )`)
  }
}

// @ID: logistics
// @CREATE: [{"key":"deliveryMode.enableExpress","value":"1"},{"key":"deliveryMode.enableLocal","value":"0"},{"key":"deliveryMode.enableSelf","value":"0"},{"key":"express.kd100.appKey","value":""},{"key":"express.kd100.customer","value":""},{"key":"selfPickup.days","value":"[1, 2, 3, 4, 5, 6, 7]"},{"key":"selfPickup.timeFrames","value":"[[\"9:00\", \"23:00\"]]"},{"key":"selfPickup.timeStep","value":"30"}]
// @UPDATE: []
// @RESTORE: []
// @REMOVE: []
// -------------------------------------------------
// Generated by XiaoShop API Client
