import { MigrationInterface, QueryRunner } from 'typeorm'

export class AssetsSettings1723186931106 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`INSERT INTO \`manage_settings\` (\`key\`, \`value\`) VALUES 
      ('assets.image.enableCompress', '1'),
      ('assets.image.compressQuality', '90'),
      ('assets.image.enableThumbnail', '1'),
      ('assets.image.thumbnailLargeWidth', '800'),
      ('assets.image.thumbnailLargeHeight', '800'),
      ('assets.image.thumbnailMediumWidth', '400'),
      ('assets.image.thumbnailMediumHeight', '400'),
      ('assets.image.thumbnailSmallWidth', '100'),
      ('assets.image.thumbnailSmallHeight', '100'),
      ('assets.image.enableWatermark', '1'),
      ('assets.image.watermarkType', 'text'),
      ('assets.image.watermarkTextValue', 'XiaoShop'),
      ('assets.image.watermarkTextSize', '16'),
      ('assets.image.watermarkTextColor', '#000000'),
      ('assets.image.watermarkTextPosition', 'center'),
      ('assets.image.watermarkTextX', '10'),
      ('assets.image.watermarkTextY', '10'),
      ('assets.image.watermarkImageSrc', ''),
      ('assets.image.watermarkImagePosition', 'center'),
      ('assets.image.watermarkImageOpacity', '100'),
      ('assets.image.watermarkImageZoom', '20'),
      ('assets.image.watermarkImageX', '10'),
      ('assets.image.watermarkImageY', '10')
    `)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DELETE FROM \`manage_settings\` WHERE \`key\` IN (
      'assets.image.enableCompress',
      'assets.image.compressQuality',
      'assets.image.enableThumbnail',
      'assets.image.thumbnailLargeWidth',
      'assets.image.thumbnailLargeHeight',
      'assets.image.thumbnailMediumWidth',
      'assets.image.thumbnailMediumHeight',
      'assets.image.thumbnailSmallWidth',
      'assets.image.thumbnailSmallHeight',
      'assets.image.enableWatermark',
      'assets.image.watermarkType',
      'assets.image.watermarkTextValue',
      'assets.image.watermarkTextSize',
      'assets.image.watermarkTextColor',
      'assets.image.watermarkTextPosition',
      'assets.image.watermarkTextX',
      'assets.image.watermarkTextY',
      'assets.image.watermarkImageSrc',
      'assets.image.watermarkImagePosition',
      'assets.image.watermarkImageOpacity',
      'assets.image.watermarkImageZoom',
      'assets.image.watermarkImageX',
      'assets.image.watermarkImageY'
    )`)
  }
}

// @ID: assets
// @CREATE: [{"key":"image.enableCompress","value":"1"},{"key":"image.compressQuality","value":"90"},{"key":"image.enableThumbnail","value":"1"},{"key":"image.thumbnailLargeWidth","value":"800"},{"key":"image.thumbnailLargeHeight","value":"800"},{"key":"image.thumbnailMediumWidth","value":"400"},{"key":"image.thumbnailMediumHeight","value":"400"},{"key":"image.thumbnailSmallWidth","value":"100"},{"key":"image.thumbnailSmallHeight","value":"100"},{"key":"image.enableWatermark","value":"1"},{"key":"image.watermarkType","value":"text"},{"key":"image.watermarkTextValue","value":"XiaoShop"},{"key":"image.watermarkTextSize","value":"16"},{"key":"image.watermarkTextColor","value":"#000000"},{"key":"image.watermarkTextPosition","value":"center"},{"key":"image.watermarkTextX","value":"10"},{"key":"image.watermarkTextY","value":"10"},{"key":"image.watermarkImageSrc","value":""},{"key":"image.watermarkImagePosition","value":"center"},{"key":"image.watermarkImageOpacity","value":"100"},{"key":"image.watermarkImageZoom","value":"20"},{"key":"image.watermarkImageX","value":"10"},{"key":"image.watermarkImageY","value":"10"}]
// @UPDATE: []
// @RESTORE: []
// @REMOVE: []
// -------------------------------------------------
// Generated by XiaoShop API Client
