import { MigrationInterface, QueryRunner } from 'typeorm'

export class UploadSettings1723089487311 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`INSERT INTO \`manage_settings\` (\`key\`, \`value\`) VALUES 
      ('upload.maxFileSizeImage', '2500'),
      ('upload.maxFileSizeVideo', '10000'),
      ('upload.customDomain', ''),
      ('upload.storage.aliyun.enable', '0'),
      ('upload.storage.aliyun.accessKeyID', ''),
      ('upload.storage.aliyun.accessKeySecret', ''),
      ('upload.storage.aliyun.bucket', ''),
      ('upload.storage.aliyun.endpoint', ''),
      ('upload.storage.aliyun.enableCustomDomain', '0'),
      ('upload.storage.aliyun.customDomain', '')
    `)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DELETE FROM \`manage_settings\` WHERE \`key\` IN (
      'upload.maxFileSizeImage',
      'upload.maxFileSizeVideo',
      'upload.customDomain',
      'upload.storage.aliyun.enable',
      'upload.storage.aliyun.accessKeyID',
      'upload.storage.aliyun.accessKeySecret',
      'upload.storage.aliyun.bucket',
      'upload.storage.aliyun.endpoint',
      'upload.storage.aliyun.enableCustomDomain',
      'upload.storage.aliyun.customDomain'
    )`)
  }
}

// @ID: upload
// @CREATE: [{"key":"maxFileSizeImage","value":"2500"},{"key":"maxFileSizeVideo","value":"10000"},{"key":"customDomain","value":""},{"key":"storage.aliyun.enable","value":"0"},{"key":"storage.aliyun.accessKeyID","value":""},{"key":"storage.aliyun.accessKeySecret","value":""},{"key":"storage.aliyun.bucket","value":""},{"key":"storage.aliyun.endpoint","value":""},{"key":"storage.aliyun.enableCustomDomain","value":"0"},{"key":"storage.aliyun.customDomain","value":""}]
// @UPDATE: []
// @RESTORE: []
// @REMOVE: []
// -------------------------------------------------
// Generated by XiaoShop API Client
