import { example as sku } from '@/product/sku/dto/example'

export const example = {
  uuid: '1111-1111-1111-1111',
  type: 1,
  status: 1,
  source: 1,
  skus: [sku],
  categories: [{ id: 1, parentId: 0, name: '分类名称' }],
  tagId: 1,
  tag: { id: 1, color: 'red', name: '标签名称' },
  groupId: 1,
  group: { id: 1, name: '分组名称' },
  brandId: 1,
  brand: { id: 1, name: '品牌名称' },
  name: '商品名称',
  desc: '商品介绍',
  slogan: '商品卖点',
  images: ['/path/to/image1', '/path/to/image2'],
  video: '/path/to/video',
  attributes: [{ name: '颜色', value: '红色' }],
  commitments: [{ id: 1, name: '承诺', icon: 'icon-name' }],
  additions: [{ id: 1, name: '附加', icon: 'icon-name', price: 100 }],
  price: 100,
  inventory: 100,
  enableVipDiscount: 1,
  enablePurchaseLimits: 1,
  purchaseMaxQty: 0,
  purchaseMinQty: 1,
  inventoryDeductMode: 1,
  deliveryMethods: [1],
  freightChargeMode: 1,
  freight: 0,
  freightTemplateId: 1,
  returnsFreightBy: 1,
  publishMode: 'auto',
  autoInStockAt: '2020-01-01 00:00:00',
  buyBtnNameType: 1,
  buyBtnName: '立即购买',
  detail: '商品详情 HTML',
  sort: 1,
  sales: 100,
  views: 100,
  favorites: 100,
  overallGrade: 1,
  overallProductScore: 5,
  overallServiceScore: 5,
  overallLogisticsScore: 5,
  isMultiSkus: 1,
  isDeleted: 0,
  isWarning: 0,
}
