export const profile = {
  status: 'normal',
  source: 'manual',
  group: { id: 1, name: 'group' },
  tags: [
    { id: 1, name: 'tag' },
  ],
  account: {
    orders: 0,
    order_amount: 0,
    exp: 0,
    points: 0,
    balance: 0,
    sign_in: 0,
    red_packet: 0,
    coupon: 0,
  },
  bindInfo: {
    id: 1,
    cardId: 1,
    cardPlanId: 1,
    name: 'Member Level 0',
    type: 'custom',
    badgeStyles: {
      icon: 'icon',
      textColor: '#000000',
      bgColor: '#ffffff',
    },
  },
  card: {
    id: 1,
    memberId: 1,
    cardId: 1,
    cardPlanId: 1,
    key: 'lv0',
    name: 'Member Level 0',
    desc: 'Member Level 0',
    type: 'level',
    planType: 'times',
    discount: 0,
    pointsRatio: 0,
    isFreeShipping: 'Y',
    isUpgradeable: 'Y',
    needExp: 100,
    nextNeedExp: 200,
    times: 1,
    cardStyles: {
      icon: 'icon',
      textColor: '#000000',
      bgColor: '#ffffff',
      bgImage: 'https://i.pravatar.cc/300',
    },
    badgeStyles: {
      icon: 'icon',
      textColor: '#000000',
      bgColor: '#ffffff',
    },
    dueTime: 1131221213,
    createdTime: '2022-01-01 00:00:00',
  },
  cardNo: '1234567890',
  avatar: 'https://i.pravatar.cc/300',
  username: 'username',
  nickname: 'nickname',
  mobile: '1450000009',
  gender: 'unknown',
  birthday: '2000-01-01',
  location: [{ id: 1, name: '北京市' }, { id: 1100, name: '北京市' }],
  createdTime: '2020-01-01 00:00:00',
  lastLoginTime: '2020-01-01 00:00:00',
}
