export const example = {
  status: 'normal',
  source: 'wechat-mp',
  tags: [
    { id: 1, name: '标签', color: 'cyan' },
  ],
  groupId: 1,
  group: { id: 1, name: '群体' },
  cardId: 1,
  card: {
    id: 1,
    key: 'svip1',
    name: '会员卡',
    cardType: 'custom',
    cardStyle: { icon: '', textColor: '#fff', bgColor: '#000', bgImage: 'https://cdn.xiaoshop.cn/card.png' },
    badgeStyle: { icon: '', textColor: '#000', bgColor: '#fff' },
    discount: 100,
    needExp: 1000,
    nextLevelExp: 0,
    freeShipping: 'Y',
    upgradeable: 'N',
    times: 0,
    dueTime: '2021-01-01 00:00:00',
  },
  cardNo: '123456',
  avatar: 'https://cdn.xiaoshop.cn/avatar.png',
  username: 'xiaoshop',
  nickname: '小欮',
  mobile: '13500000001',
  birthday: '2000-01',
  gender: 'male',
  location: [{ code: '11', name: '北京' }, { code: '1100', name: '市区' }],
  exp: 0,
  points: 0,
  balance: 0,
  orders: 0,
  orderAmount: 0,
  signInTimes: 0,
  loginTimes: 0,
  redPacket: 0,
  coupon: 0,
}
